#!/bin/sh
# build.sh — generate install.sh: bootstrap.sh with keys/authorized.pub and
# keys/ca.pub embedded, so it can be curled straight into sh with no sibling
# keys/ directory needed.
#
#   ./build.sh
#   curl -fsSL .../install.sh | sh
#
# install.sh is a build artifact (gitignored) — edit bootstrap.sh or keys/,
# then re-run this. Never edit install.sh directly; it will be overwritten.

set -eu

SELF_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
SRC=$SELF_DIR/bootstrap.sh
KEY=$SELF_DIR/keys/authorized.pub
CA=$SELF_DIR/keys/ca.pub
OUT=$SELF_DIR/install.sh

# bootstrap.sh carries a matching comment marking where its scratch $TMP has
# just been created and trapped for cleanup — the safe place to drop our
# embedded key material into that same directory.
MARK='# build.sh: embedded keys/, if any, are spliced in right after this line.'

[ -f "$SRC" ] || { echo "build.sh: missing $SRC" >&2; exit 1; }
[ -f "$KEY" ] || { echo "build.sh: missing $KEY" >&2; exit 1; }
[ -f "$CA" ]  || { echo "build.sh: missing $CA" >&2; exit 1; }

n=$(grep -cF "$MARK" "$SRC")
[ "$n" -eq 1 ] || {
    echo "build.sh: expected exactly one '$MARK' line in $SRC (the \$TMP" >&2
    echo "cleanup trap) to splice after — found $n. bootstrap.sh changed" >&2
    echo "shape; update build.sh's MARK." >&2
    exit 1
}

# Emit a quoted heredoc writing $2's contents to path $1 (written literally,
# unexpanded — $1 is meant to contain a $TMP reference resolved when the
# *generated* script runs, not now).
embed() {
    printf 'cat <<'"'"'__BOOTSTRAP_GEN_EOF__'"'"' > "%s"\n' "$1"
    cat "$2"
    printf '__BOOTSTRAP_GEN_EOF__\n'
}

{
    head -n1 "$SRC"
    printf '# GENERATED by build.sh from bootstrap.sh + keys/ — do not edit by hand.\n'
    tail -n +2 "$SRC" | awk -v m="$MARK" '{print; if (index($0,m)) exit}'
    embed '$TMP/authorized.pub' "$KEY"
    embed '$TMP/ca.pub' "$CA"
    printf ': "${KEY_FILE:=$TMP/authorized.pub}"\n'
    printf ': "${CA_FILE:=$TMP/ca.pub}"\n'
    tail -n +2 "$SRC" | awk -v m="$MARK" 'f{print} index($0,m){f=1}'
} > "$OUT"

chmod +x "$OUT"
echo "wrote $OUT"
